# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest


steps:


- task: UsePythonVersion@0
  inputs:
      versionSpec: '3.10'
      addToPath: true
      architecture: 'x64'

- script: |
    mkdir export
  displayName: "Create export directory"

- script: |
    cd python
    python3 -m pip install --upgrade build
    python3 -m build
    pip3 install pytest pytest-azurepipelines pytest-asyncio  
    pip3 install -e .
  displayName: 'Build mdedevicecontrol'

  

- script: |
    pwd
    cd python
    python -m pytest tests/ -W ignore::DeprecationWarning

  displayName: 'Run pytest'
  env:
    TENANT_ID: $(tenantId)
    CLIENT_ID: $(clientId)
    CLIENT_SECRET: $(clientSecret)
  continueOnError: true

- script: |
    cd python
    cat mdedevicecontrol.log
  displayName: 'Show Logs'

- publish: $(System.DefaultWorkingDirectory)/export
  displayName: 'Intune Export'
